<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>PequenasFinancas.App</RootNamespace>
    <AssemblyName>PequenasFinancas</AssemblyName>
    <ApplicationTitle>Pequenas Finanças</ApplicationTitle>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <RuntimeHostConfigurationOption Include="Switch.System.Windows.DoNotScaleForDpiChanges" Value="false" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PequenasFinancas.Core\PequenasFinancas.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="10.0.90" />
  </ItemGroup>

</Project>
